[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000029482B93C50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/f1594090dd0a5198640a87436f21bc5d
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000029482B93ED0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/f1594090dd0a5198640a87436f21bc5d
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000029482623E10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/f1594090dd0a5198640a87436f21bc5d