[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000029504714190>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/02782ecf4f7d12630ee58904b1b9b197/execute/sync
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000029504714550>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/02782ecf4f7d12630ee58904b1b9b197/execute/sync
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002950460AB10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/02782ecf4f7d12630ee58904b1b9b197/execute/sync